#include <iostream>
#include <exception>


int main()
{
    throw std::exception("Error!");

}